image: fischerscode/flutter

pipelines:
  branches:
    master:
      - step:
          max-time: 120
          size: 2x
          script:
            - export ANDROID_SDK_ROOT=C:\Users\dilee\AppData\Local\Android\Sdk
            - export ANDROID_HOME=C:\Users\dilee\AppData\Local\Android\Sdk
            - flutter --version
            - flutter upgrade
            - flutter pub get
            - flutter analyze
            - flutter build apk
          trigger: automatic
          artifacts:
            - "build/app/output/apk/release/*"
