image: fischerscode/flutter

pipelines:
  branches:
    master:
      - step:
          max-time: 120
          size: 2x
          script:
            - export ANDROID_SDK_ROOT=/opt/android-sdk  # Use the path within the image
            - export ANDROID_HOME=/opt/android-sdk
            - flutter --version
            - flutter upgrade
            - flutter pub get
            - flutter analyze
            - flutter build apk
          trigger: automatic
          artifacts:
            - "build/app/output/apk/release/*"
