image: fischerscode/flutter

pipelines:
  branches:
    master:
      - step:
          size: 2x
          script:
            - flutter pub get
            - flutter analyze
            - flutter build apk
          trigger: automatic
          artifacts:
            - "build/app/output/apk/release/*"
